name: Issue to PR with Codex

on:
  issues:
    types: [opened, labeled]

jobs:
  fix_with_codex:
    runs-on: ubuntu-latest
    # codexラベルが付いているissueのみ実行
    if: contains(github.event.issue.labels.*.name, 'codex')

    permissions:         # gh コマンドで PR を作るため
      contents: write    # push
      pull-requests: write
      actions: write     # GitHub Actions からの PR 作成を許可

    steps:
      - uses: actions/checkout@v4

      - name: Set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install Codex CLI
        run: npm install -g @openai/codex  # Codex CLI は npm グローバルで OK  [oai_citation:0‡GitHub](https://github.com/openai/codex)

      - name: Generate patch with Codex
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # ブランチ名を決定
          BRANCH="codex/issue-${{ github.event.issue.number }}"
          git switch -c "$BRANCH"

          # npm関連のクリーンアップ
          if [ -d "node_modules" ]; then
            rm -rf node_modules
          fi
          if [ -f "package-lock.json" ]; then
            rm package-lock.json
          fi

          # Issue タイトル + 本文をプロンプト化
          PROMPT="$(printf '%s\n\n%s\n%s\n' "${{ github.event.issue.title }}" "${{ github.event.issue.body }}" "最後に\`npm ci && npm run build\`を実行してエラーが出ないことを確認してください。 .gitのような'.'から始まるファイル、フォルダの中身は絶対に変更しないでください。")"

          # --full-auto は "自動で編集して commit まで" 行うモード
          codex -a full-auto --quiet "$PROMPT"

          # 変更があった場合に確実にコミット
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Fix: #${{ github.event.issue.number }} - ${{ github.event.issue.title }}"
          fi

          # 変更加えて commit が出来ている想定で push
          git push -u origin "$BRANCH"

      - name: Create Pull Request
        env:
          # GitHub Actions から PR を作成するために Personal Access Token が必要
          # Repository Settings > Secrets and variables > Actions で 
          # PAT_TOKEN という名前で Personal Access Token を設定してください
          # 権限: repo, workflow
          GH_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Fix: #${{ github.event.issue.number }} – ${{ github.event.issue.title }}" \
            --body  "Automated fix generated by Codex CLI." \
            --base  main \
            --head  "$BRANCH" 