name: Issue to PR with Codex

on:
  issues:
    types: [opened]

jobs:
  fix_with_codex:
    runs-on: ubuntu-latest

    permissions:         # gh コマンドで PR を作るため
      contents: write    # push
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install Codex CLI
        run: npm install -g @openai/codex  # Codex CLI は npm グローバルで OK  [oai_citation:0‡GitHub](https://github.com/openai/codex)

      - name: Generate patch with Codex
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # ブランチ名を決定
          BRANCH="codex/issue-${{ github.event.issue.number }}"
          git switch -c "$BRANCH"

          # Issue タイトル + 本文をプロンプト化
          PROMPT="$(printf '%s\n\n%s' "${{ github.event.issue.title }}" "${{ github.event.issue.body }}")"

          # --full-auto は "自動で編集して commit まで" 行うモード
          codex -a full-auto --quiet "$PROMPT"

          # 変更加えて commit が出来ている想定で push
          git push -u origin "$BRANCH"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Fix: #${{ github.event.issue.number }} – ${{ github.event.issue.title }}" \
            --body  "Automated fix generated by Codex CLI." \
            --base  main \
            --head  "$BRANCH" \
            --label "codex-auto"