name: Issue to PR with Codex

on:
  issues:
    types: [labeled]

jobs:
  fix_with_codex:
    runs-on: ubuntu-latest
    # codexラベルが追加された時のみ実行
    if: github.event.label.name == 'codex'

    permissions:         # gh コマンドで PR を作るため
      contents: write    # push
      pull-requests: write
      actions: write     # GitHub Actions からの PR 作成を許可

    steps:
      - uses: actions/checkout@v4

      - name: Set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm ci

      - name: Install Codex CLI
        run: npm install -g @openai/codex  # Codex CLI は npm グローバルで OK  [oai_citation:0‡GitHub](https://github.com/openai/codex)

      # 画像を TEMP_IMG に保存（repo 外なので git add 対象にならない）
      - name: Download all screenshots
        id: dl_images
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          TEMP_DIR="$RUNNER_TEMP/issue_imgs"
          echo "TEMP_DIR=$TEMP_DIR" >> "$GITHUB_ENV"
          mkdir -p "$TEMP_DIR"
          
          echo "$ISSUE_BODY" | \
            grep -oE 'https://[^ )]+(\.(png|jpe?g|gif|webp|svg)|/user-attachments/assets/[0-9a-fA-F-]+)' | \
            while IFS= read -r url; do
              fname=$(basename "${url%%\?*}")
              echo "Downloading: $url"
              curl -sSLJ \
                    -H "Authorization: Bearer $GH_TOKEN" \
                    -o "$TEMP_DIR/$fname.png" "$url" || echo "Failed to download: $url"
            done
          # 最後にTEMP_DIRの中身を表示
          echo "TEMP_DIR=$TEMP_DIR" >> "$GITHUB_ENV"
          ls -la "$TEMP_DIR"

      - name: Generate patch with Codex
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # ブランチ名を決定(codex/issue-${{ github.event.issue.number }}-{uuid})
          BRANCH="codex/issue-${{ github.event.issue.number }}-$(uuidgen)"
          git checkout -B "$BRANCH"

          # Issue タイトル + 本文をプロンプト化
          PROMPT="$(printf '%s\n\n%s\n%s\n' "${{ github.event.issue.title }}" "${{ github.event.issue.body }}" "最後に\`npm run build\`を実行してエラーが出ないことを確認してください。 .gitのような'.'から始まるファイル、フォルダの中身は絶対に変更しないでください。")"

          # 画像ファイルを配列で収集
          IMAGE_FILES=()
          if [ -d "$TEMP_DIR" ]; then
            while IFS= read -r -d '' file; do
              IMAGE_FILES+=("$file")
            done < <(find "$TEMP_DIR" -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" -o -name "*.webp" -o -name "*.svg" \) -print0)
          fi

          echo "IMAGE_FILES=${#IMAGE_FILES[@]}" >> "$GITHUB_ENV"

          # --full-auto は "自動で編集して commit まで" 行うモード
          if [ ${#IMAGE_FILES[@]} -gt 0 ]; then
            # 画像ファイルがある場合は -i オプションで渡す
            codex_args=(-a full-auto --quiet)
            for img in "${IMAGE_FILES[@]}"; do
              codex_args+=(-i "$img")
            done
            codex_args+=("$PROMPT")
            codex "${codex_args[@]}"
          else
          codex -a full-auto --quiet "$PROMPT"
          fi

          # 変更があった場合に確実にコミット
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Fix: #${{ github.event.issue.number }} - ${{ github.event.issue.title }}"
          fi

          # 変更加えて commit が出来ている想定で push
          git push -u origin "$BRANCH"

      - name: Create Pull Request
        env:
          # GitHub Actions から PR を作成するために Personal Access Token が必要
          # Repository Settings > Secrets and variables > Actions で 
          # PAT_TOKEN という名前で Personal Access Token を設定してください
          # 権限: repo, workflow
          GH_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Fix: #${{ github.event.issue.number }} – ${{ github.event.issue.title }}" \
            --body  "Automated fix generated by Codex CLI." \
            --base  main \
            --head  "$BRANCH" 